version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    image: raghavpatnecha/asper-wallet-api:0.0.1.RELEASE
    ports:
      - "5000:5000"
    volumes:
      - .:/usr/src/app